name: clear_stream
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^6.0.1
  flutter_osm_plugin: ^0.70.0
  fluttertoast: ^8.2.4
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  image_picker: ^1.0.4
  latlong2: ^0.9.0
  location: ^5.0.3
  permission_handler: ^10.4.5
  provider: ^6.0.5
  http: ^1.1.0
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  flutter_form_builder: ^9.1.1
  dio: ^5.3.4
  flutter_map_cancellable_tile_provider: ^1.0.0
  routing_client_dart: ^0.4.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
