// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxlTOqX0arEr6oIl0DOuBrkwJH7md8CI',
    appId: '1:1088643948830:web:45f1c231d29adc5a24290f',
    messagingSenderId: '1088643948830',
    projectId: 'clear-stram',
    authDomain: 'clear-stram.firebaseapp.com',
    storageBucket: 'clear-stram.appspot.com',
    measurementId: 'G-RRRKZCYMH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0r40nzf5MCO0SplIOwGhYLKPisfzoPQA',
    appId: '1:1088643948830:android:8caffa775eda22ed24290f',
    messagingSenderId: '1088643948830',
    projectId: 'clear-stram',
    storageBucket: 'clear-stram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmagppLioA2GIwJcOQuH3l39gUA9DVXKc',
    appId: '1:1088643948830:ios:07577a81d9c8cb9624290f',
    messagingSenderId: '1088643948830',
    projectId: 'clear-stram',
    storageBucket: 'clear-stram.appspot.com',
    iosBundleId: 'com.example.clearStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmagppLioA2GIwJcOQuH3l39gUA9DVXKc',
    appId: '1:1088643948830:ios:13cef1d2ec33b19e24290f',
    messagingSenderId: '1088643948830',
    projectId: 'clear-stram',
    storageBucket: 'clear-stram.appspot.com',
    iosBundleId: 'com.example.clearStream.RunnerTests',
  );
}
