// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqckKn7KDQTYCjtBhstIuxPXRq_ulXhjs',
    appId: '1:987596278870:web:30bef3a09a228077207ff7',
    messagingSenderId: '987596278870',
    projectId: 'clear-stream-429bf',
    authDomain: 'clear-stream-429bf.firebaseapp.com',
    storageBucket: 'clear-stream-429bf.appspot.com',
    measurementId: 'G-SRFT5DL69R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DIjdyEn14mM2s_JIL9CUDHFCaFK6wK0',
    appId: '1:987596278870:android:2dc2be8e61fd4f1e207ff7',
    messagingSenderId: '987596278870',
    projectId: 'clear-stream-429bf',
    storageBucket: 'clear-stream-429bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_yrD9LTo6nqvsb3gTHIrU23l-bg9gIjM',
    appId: '1:987596278870:ios:4854472ecae17b92207ff7',
    messagingSenderId: '987596278870',
    projectId: 'clear-stream-429bf',
    storageBucket: 'clear-stream-429bf.appspot.com',
    iosBundleId: 'com.example.clearStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_yrD9LTo6nqvsb3gTHIrU23l-bg9gIjM',
    appId: '1:987596278870:ios:7748a97c5e837b94207ff7',
    messagingSenderId: '987596278870',
    projectId: 'clear-stream-429bf',
    storageBucket: 'clear-stream-429bf.appspot.com',
    iosBundleId: 'com.example.clearStream.RunnerTests',
  );
}
